org: fabulousplastic
service: message-board-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  
  environment:
    MESSAGES_TABLE: shuiMessages  # Pass the table name as an environment variable
  
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"  # Scope this down as needed to the actual table ARN

functions:
  createMessage:
    handler: handler.handler
    events:
      - http:
          path: /message
          method: post
          cors: true

  updateMessage:
    handler: handler.handler
    events:
      - http:
          path: /message/{messageId}
          method: put
          cors: true

  getMessages:
    handler: handler.handler
    events:
      - http:
          path: /messages
          method: get
          cors: true

  getMessagesByUser:
    handler: handler.handler
    events:
      - http:
          path: /messages/user/{userId}
          method: get
          cors: true

resources:
  Resources:
    ShuiMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shuiMessages
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - README.md
    - package-lock.json
    - message-board-frontend/**