org: fabulousplastic
service: message-board-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1  
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"  # Scope this down to the actual table ARN in production
      # managedPolicies:
      #   - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole    

  httpApi:
    cors:
      allowedOrigins:
        - '*'  # Allow all origins.
      allowedMethods:
        - GET
        - POST
        - PUT
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token

  environment:
    MESSAGES_TABLE: shuiMessages
  

functions:
  app:
    handler: handler.handler
    events:
      - httpApi:
          path: /message
          method: post
      - httpApi:
          path: /message/{messageId}
          method: put
      - httpApi:
          path: /messages
          method: get
      - httpApi:
          path: /messages/user/{userId}
          method: get

resources:
  Resources:
    ShuiMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shuiMessages
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL


package:
  exclude:
    - node_modules/aws-sdk/**
    - .git/**
    - .vscode/**
    - README.md
    - message-board-frontend/**